/**
 * Drizzle migration runner for Effect.
 *
 * Uses drizzle-orm's Effect-native migrator to run pending migrations.
 * Migrations are generated by `drizzle-kit generate` and stored in
 * the `drizzle/` directory at the package root.
 *
 * Usage:
 *
 *   import { DB, DrizzleLive } from "@repo/database/client";
 *   import { runMigrations } from "@repo/database/migrator";
 *
 *   const program = Effect.gen(function* () {
 *     const db = yield* DB;
 *     yield* runMigrations(db);
 *   });
 */

import path from "node:path";
import { fileURLToPath } from "node:url";
import type { EffectPgDatabase } from "drizzle-orm/effect-postgres";
import { migrate } from "drizzle-orm/effect-postgres/migrator";
import { Effect } from "effect";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const defaultMigrationsFolder = path.resolve(__dirname, "../../drizzle");

/**
 * Run all pending Drizzle migrations.
 *
 * @param db - The Drizzle database instance from the DB Tag
 * @param migrationsFolder - Optional override for the migrations folder path
 */
export const runMigrations = (
  // biome-ignore lint/suspicious/noExplicitAny: Drizzle's EffectPgDatabase requires generic type params
  db: EffectPgDatabase<any, any>,
  migrationsFolder = defaultMigrationsFolder,
) =>
  migrate(db, { migrationsFolder }).pipe(
    Effect.catchAllDefect((defect) =>
      Effect.fail(new Error(`Migration failed: ${defect}`, { cause: defect })),
    ),
  );
