#!/usr/bin/env bash
#
# sst-bootstrap.sh — get a fresh clone ready to deploy with SST.
#
# What it does:
#   1. Generates .sst/ provider types (gitignored, not present on fresh clone),
#      so sst.config.ts + infra/ typecheck and editors stop complaining.
#   2. Checks the AWS CLI and your selected profile can reach an account.
#   3. Persists *non-secret* choices (profile, region, stage) to a gitignored
#      sst.env.local you can `source` before running sst commands.
#   4. Optionally generates + stores the internal-auth secret in SST for a stage.
#
# It does NOT write AWS access keys anywhere in the repo. Credentials live in
# ~/.aws (via `aws configure sso` / `aws configure`); SST secrets live in AWS
# SSM (via `sst secret set`), never in git.
#
# Usage:
#   pnpm sst:bootstrap            # interactive
#   CI=1 pnpm sst:bootstrap       # non-interactive: only step 1 (sst install)

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m'

info()  { printf "${GREEN}[sst-bootstrap]${NC} %s\n" "$1"; }
warn()  { printf "${YELLOW}[sst-bootstrap]${NC} %s\n" "$1"; }
fail()  { printf "${RED}[sst-bootstrap]${NC} %s\n" "$1"; exit 1; }

LOCAL_ENV="sst.env.local"

# Non-interactive if no TTY or CI is set.
interactive=1
if [ ! -t 0 ] || [ "${CI:-}" = "1" ] || [ "${CI:-}" = "true" ]; then
  interactive=0
fi

prompt() { # prompt <var> <message> <default>
  local __var="$1" __msg="$2" __def="${3:-}"
  if [ "$interactive" -eq 0 ]; then
    printf -v "$__var" '%s' "$__def"
    return
  fi
  local __input
  read -r -p "$(printf "${YELLOW}? ${NC}%s [%s]: " "$__msg" "$__def")" __input
  printf -v "$__var" '%s' "${__input:-$__def}"
}

# ---------------------------------------------------------------------------
# 1. Generate SST provider types (.sst/)
# ---------------------------------------------------------------------------
info "Generating SST platform types (.sst/) ..."
pnpm exec sst install
info ".sst/ ready — sst.config.ts + infra/ will now typecheck."

if [ "$interactive" -eq 0 ]; then
  info "Non-interactive run — skipping AWS config. Done."
  exit 0
fi

# ---------------------------------------------------------------------------
# 2. AWS CLI presence
# ---------------------------------------------------------------------------
if ! command -v aws > /dev/null 2>&1; then
  warn "AWS CLI not found. Install it: https://aws.amazon.com/cli/"
  warn "Re-run this script once the AWS CLI is available to finish AWS setup."
  exit 0
fi

# ---------------------------------------------------------------------------
# 3. Gather choices (non-secret)
# ---------------------------------------------------------------------------
prompt AWS_PROFILE_CHOICE "AWS profile to deploy with" "${AWS_PROFILE:-bedrock-dev}"
prompt AWS_REGION_CHOICE  "AWS region"                  "${AWS_REGION:-eu-west-1}"
prompt SST_STAGE_CHOICE   "SST stage"                   "$(whoami)"

# ---------------------------------------------------------------------------
# 4. Verify (or set up) credentials for the profile
# ---------------------------------------------------------------------------
if aws sts get-caller-identity --profile "$AWS_PROFILE_CHOICE" > /dev/null 2>&1; then
  ACCOUNT=$(aws sts get-caller-identity --profile "$AWS_PROFILE_CHOICE" --query Account --output text)
  info "Profile '$AWS_PROFILE_CHOICE' authenticated (account $ACCOUNT)."
else
  warn "Profile '$AWS_PROFILE_CHOICE' can't reach AWS yet."
  prompt SETUP_KIND "Configure it now? (sso / keys / skip)" "sso"
  case "$SETUP_KIND" in
    sso)  aws configure sso --profile "$AWS_PROFILE_CHOICE" ;;
    keys) aws configure --profile "$AWS_PROFILE_CHOICE" ;;
    *)    warn "Skipping credential setup — do it before 'sst deploy'." ;;
  esac
fi

# ---------------------------------------------------------------------------
# 5. Persist non-secret choices to a gitignored env file
# ---------------------------------------------------------------------------
cat > "$LOCAL_ENV" <<EOF
# Generated by tooling/scripts/sst-bootstrap.sh — gitignored, non-secret.
# Source before sst commands:  set -a && source $LOCAL_ENV && set +a
export AWS_PROFILE=$AWS_PROFILE_CHOICE
export AWS_REGION=$AWS_REGION_CHOICE
export SST_STAGE=$SST_STAGE_CHOICE
EOF
info "Wrote $LOCAL_ENV (profile/region/stage). It is gitignored."

# ---------------------------------------------------------------------------
# 6. Optionally set the internal-auth secret for the stage
# ---------------------------------------------------------------------------
prompt SET_SECRET "Generate + store ApiInternalAuthToken for stage '$SST_STAGE_CHOICE'? (y/N)" "N"
case "$SET_SECRET" in
  y|Y|yes)
    if ! command -v openssl > /dev/null 2>&1; then
      warn "openssl not found — set it manually: pnpm sst secret set ApiInternalAuthToken <value> --stage $SST_STAGE_CHOICE"
    else
      TOKEN=$(openssl rand -hex 32)
      AWS_PROFILE="$AWS_PROFILE_CHOICE" AWS_REGION="$AWS_REGION_CHOICE" \
        pnpm exec sst secret set ApiInternalAuthToken "$TOKEN" --stage "$SST_STAGE_CHOICE"
      info "ApiInternalAuthToken set for stage '$SST_STAGE_CHOICE'."
    fi
    ;;
  *) info "Skipped secret. Set it before deploy if not already done." ;;
esac

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------
info "Bootstrap complete. Next:"
printf "  set -a && source %s && set +a\n" "$LOCAL_ENV"
printf "  pnpm sst deploy --stage %s\n" "$SST_STAGE_CHOICE"
